services:
  - type: web
    name: befayer-call-calendar-387
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_PATH
        value: /tmp/calendar.db

